SELECT p.PAYMENT_ID,
p.DEPARTMENT,
p.AMOUNT,
p.payment_date_iso
FROM PAYMENT_SYSTEM p
LEFT JOIN bank_statement b 
ON p.PAYMENT_ID = b.PAYMENT_ID
WHERE b.PAYMENT_ID IS NULL
AND p.STATUS = 'SUCCESS'
;